### ISSUE TITLE
vue3项目中报错（node V10.22.0）

### ISSUE THREAD

**Issue by zhangwenwen12138** [szYuan/vue3-bus#1]
XXXX\node_modules\vue3-eventbus\src\index.js:1     
import mitt from 'mitt'
SyntaxError: Unexpected identifier
![image](https://user-images.githubusercontent.com/39935062/116200290-bb8ec500-a76a-11eb-80c2-a38de92d5cbb.png)

**Comment by szyuan** [comment]
建议升级一下node环境哈，因为node 13.2+才正式支持ESM（import方式引入模块）
因为是简单用esm写的，没有用打包工具。既然你都用上了vue3，建议把Node也升级到最新的LTS版本哈~（现在是14.16）

关于node对esm的支持信息可以参考：https://juejin.cn/post/6844904004024008711

**Comment by zhangwenwen12138** [comment]
升级node后可以修复
